### ISSUE TITLE
Large size images

### ISSUE THREAD

**Issue by Kwoalaka** [jcjohnson/neural-style#131]
Hi,
I'm new to neural style. I really like the results.
I have been trying to get some larger images, but i get stuck around 800px.
I was wondering, i have a titan x 12GB i could use. (current tesla c2075)
Is it possible to get some decent quality images out of it. I was hoping for a decent 1500px. Is there someone who managed to get a 1500px good quality result?
If so, i would love to see a example!

**Comment by Kwoalaka** [comment]
**

Forgot to mention, as said i am using a Tesla c2075 6gb. Without any trouble i can push the size up to 800px. But when i go higher, it gives the "run out of memory" error. I checked the GPU usage with  `<nvidia-smi>` and it says while running 800px the usage is about 3000MB Ram. I assumed to get high resolutions, you need lots of ram. But there are any more factors that have influence?

**Comment by jcjohnson** [comment]
You can try the tips here for reducing memory usage:

https://github.com/jcjohnson/neural-style#memory-usage

With a Titan X you should be able to make images at 1500px. Here's an example I did a while back; you could probably do better with better tuning of parameters:

http://imgur.com/a/SSIaB

**Comment by Kwoalaka** [comment]
Hi,

Thanks for your fast reply. 

It's more about the definition "memory usage". I assumed it points to the ram usage of the gpu. The bigger the gpu's ram, the higher the result. 

The thing, my tesla uses about 3000mb (6000 total) ram for 750px, why does it run out of "memory usage" when trying to get 800px. Its only 50px more so it should never use the full 3000mb ram left. 

I thought Gpu ram size = image output size

It seems there are some other limitations besides the ram

Is there some more information about the gpu usage?

**Comment by jcjohnson** [comment]
Yes, "memory usage" refers to GPU memory since that is usually the bottleneck.

With default settings (nn backend and L-BFGS) generating a 750px image takes just over 6GB on my system; running on a 6GB card, it runs for a few iterations then crashes with "out-of-memory" while 800px crashes right away with "out-of-memory". Are you sure you're getting an accurate read on the GPU memory usage? Usually I run `watch -n 1 nvidia-smi` in another terminal to check memory usage while things run.

GPU memory usage is roughly linear in the number of pixels in the output image, making it roughly quadratic in the image size. Therefore you should expect that an 800px image takes about 15% more memory than a 750px image.

BTW, switching to the cudnn backend drastically reduces memory usage; you should be able get more than 800px out of a 6GB card using cudnn.

**Comment by Kwoalaka** [comment]
`watch -n 1 nvidia-smi`did the trick. I saw it run out ram, you were right.

Makes me wonder how they render images like these:

https://deepart-io.s3.amazonaws.com/hi-res/leon4.jpg

It's from deepart.io

These are very high resolution images, i guess they use multiple gpu's to render it?

**Comment by jcjohnson** [comment]
Good question! I'm not sure how they do it, but their results are great. Also note that deepart.io has the original authors of the algorithm onboard, so they may have some unpublished tricks.
