### ISSUE TITLE
Make sure files named as libcudnn.so.4 or libcudnn.4.dylib are placed in your library load path on OS X

### ISSUE THREAD

**Issue by canpoyrazoglu** [jcjohnson/neural-style#224]
Hello,

I've set up neural-style, I've already got CUDA on my machine, and I can run in CUDA mode. However, 2GB VRAM doesn't seem enough and I'm getting out-of-memory errors so I want to try cuDNN backend.

I've installed cuDNN 4 from NVIDIA, put it into an appropriate directory. I also ran `luarocks install cudnn` and it executed with no errors. I **do** have `libcudnn.4.dylib` in my `LD_LIBRARY_PATH` and I verify it's correct:

```
    canp:~ Can$ echo $LD_LIBRARY_PATH 
    /Users/Can/torch/install/lib:/Developer/NVIDIA/CUDA-7.5/lib
```

It's right there in `/Developer/NVIDIA/CUDA-7.5/lib`, however when I try neural-style with cuDNN backend I'm getting an error:

```
/Users/Can/torch/install/bin/luajit: /Users/Can/torch/install/share/lua/5.1/trepl/init.lua:384: /Users/Can/torch/install/share/lua/5.1/trepl/init.lua:384: /Users/Can/torch/install/share/lua/5.1/cudnn/ffi.lua:1278: 'libcudnn (R4) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.4 or libcudnn.4.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)
```

Why am I getting this even though I have the library at the correct path?

**Comment by canpoyrazoglu** [comment]
Okay, after reading this https://github.com/soumith/cudnn.torch/issues/178 I've tried copying `libcudnn` to `/usr/local/lib` and it worked.
