### ISSUE TITLE
CUDA problem and cuDNN

### ISSUE THREAD

**Issue by codesoon** [jcjohnson/neural-style#266]
I have a problem with CUDA and cuDNN:

*   th neural_style.lua -gpu 0 -print_iter 1

    ~~~
    [libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer  	2	:	relu1_1	
Setting up style layer  	7	:	relu2_1	
Setting up style layer  	12	:	relu3_1	
THCudaCheck FAIL file=/home/user/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=41 error=2 : out of memory
/home/user/torch/install/bin/luajit: /home/user/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 11 module of nn.Sequential:
/home/user/torch/install/share/lua/5.1/nn/THNN.lua:109: cuda runtime error (2) : out of memory at /home/user/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:41
stack traceback:
	[C]: in function 'v'
	/home/user/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'SpatialConvolutionMM_updateOutput'
	...er/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:112: in function <...er/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:107>
	[C]: in function 'xpcall'
	/home/user/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/user/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	neural_style.lua:204: in function 'main'
	neural_style.lua:515: in main chunk
	[C]: in function 'dofile'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/user/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/user/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	neural_style.lua:204: in function 'main'
	neural_style.lua:515: in main chunk
	[C]: in function 'dofile'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

    ~~~

***

*   luarocks install cudnn

    ~~~
    Installing https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec... switching to 'build' mode
Cloning into 'cudnn.torch'...
remote: Counting objects: 52, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 52 (delta 16), reused 21 (delta 6), pack-reused 0
Receiving objects: 100% (52/52), 50.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (16/16), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/user/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/user/torch/install/lib/luarocks/rocks/cudnn/scm-1" && make

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/user/torch/install
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA: Found unsuitable version "7.0", but required is at
  least "7.5" (found /usr/local/cuda)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindCUDA.cmake:806 (find_package_handle_standard_args)
  CMakeLists.txt:9 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cudnn-scm-1-1755/cudnn.torch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

    ~~~

**Comment by jcjohnson** [comment]
You have CUDA 7.0 and are trying to use cuDNN 5; those don't work
together.  You can either upgrade to CUDA 7.5 or downgrade to cuDNN 4

**Comment by codesoon** [comment]
My cuDNN: cudnn-7.0-linux-x64-v4.0-prod
CUDA Version: 7.0-28

**Comment by jcjohnson** [comment]
You need to install the torch bindings for cuDNN V4; the current master branch expects V5, like this:

```bash
git clone https://github.com/soumith/cudnn.torch.git
cd cudnn.torch
git checkout R4
luarocks install cudnn-scm-1.rockspec
```

**Comment by codesoon** [comment]
Ok. 
*    th neural_style.lua -gpu 0 -backend cudnn
    ~~~
/home/user/torch/install/bin/luajit: /home/user/torch/install/share/lua/5.1/trepl/init.lua:384: /home/user/torch/install/share/lua/5.1/trepl/init.lua:384: /home/user/torch/install/share/lua/5.1/cudnn/ffi.lua:1278: 'libcudnn (R4) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.4 or libcudnn.4.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
	[C]: in function 'error'
	/home/user/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	neural_style.lua:64: in function 'main'
	neural_style.lua:515: in main chunk
	[C]: in function 'dofile'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

    ~~~

**Comment by 494shah** [comment]
I'm having the same problem, not sure how to resolve. 

cuDNN 5.1 for 7.5:
```
/home/shah/torch/install/bin/luajit: /home/shah/torch/install/share/lua/5.1/trepl/init.lua:384: /home/shah/torch/install/share/lua/5.1/trepl/init.lua:384: /home/shah/torch/install/share/lua/5.1/cudnn/ffi.lua:1599: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
        [C]: in function 'error'
        /home/shah/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
        neural_style.lua:64: in function 'main'
        neural_style.lua:515: in main chunk
        [C]: in function 'dofile'
        ...shah/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```

Pretty sure this isnt really a problem and its just too large. I have a 780ti with 3gb video memory...
Cuda 7.5:
```
shah@Shah-Kub-Throne:~/neural-style$ th neural_style.lua -gpu 0 -print_iter 1
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer          2       :       relu1_1
Setting up style layer          7       :       relu2_1
Setting up style layer          12      :       relu3_1
Setting up style layer          21      :       relu4_1
Setting up content layer        23      :       relu4_2
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-6119/cutorch/lib/THC/generic/THCStorage.cu line=40 error=2 : out of memory
/home/shah/torch/install/bin/luajit: /home/shah/torch/install/share/lua/5.1/nn/utils.lua:11: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-6119/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
        [C]: in function 'resize'
        /home/shah/torch/install/share/lua/5.1/nn/utils.lua:11: in function 'torch_Storage_type'
        /home/shah/torch/install/share/lua/5.1/nn/utils.lua:57: in function 'recursiveType'
        /home/shah/torch/install/share/lua/5.1/nn/Module.lua:126: in function 'cuda'
        neural_style.lua:183: in function 'main'
        neural_style.lua:515: in main chunk
        [C]: in function 'dofile'
        ...shah/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```

**Comment by fdimitri** [comment]
The line "Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)" is important, you can do:

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to-libcudnn.so.5

ie

# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find / -name libcudnn.so.5 | tail -1)

Or add the path to your ld.so.conf, or a file containing the path in /etc/ld.so.conf.d/

ie on my FC23 box:
# cat  /etc/ld.so.conf.d/nvidia-cuda-toolkit-8.0.conf
/usr/local/cuda-8.0/lib64

Then run

# ldconfig

**Comment by codesoon** [comment]
```
echo $(dirname $(find / -name libcudnn.so.5 | tail -1))
dirname: missing operand
```
