### ISSUE TITLE
 -backend cudnn fails with "attempt to get length of local 'typeName' (a nil value)"

### ISSUE THREAD

**Issue by salamanders** [jcjohnson/neural-style#31]
I have just installed what I think is the right cudnn files in the right place... maybe?  Running OSX.  Signed up for their developer program to get the files.  Bleagh, wish I could just brew it.

.bash_profile
```
# Custom dev for torch7, cuda
export PATH=/Developer/NVIDIA/CUDA-7.5/bin:$PATH
export LD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:$LD_LIBRARY_PATH
. /Users/ME/torch/install/bin/torch-activate
```
which seems right, given I dropped off the zip's file in /Developer/NVIDIA/CUDA-7.5/lib/libcudnn.dylib etc.

However, **-backend cudnn** results in

```
th neural_style.lua -style_image self_straw.png -content_image happy_family.JPG -backend cudnn
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
/Users/ME/torch/install/bin/luajit: /Users/ME/torch/install/share/lua/5.1/torch/init.lua:101: attempt to get length of local 'typeName' (a nil value)
stack traceback:
	/Users/ME/torch/install/share/lua/5.1/torch/init.lua:101: in function 'matchFunc'
	/Users/ME/torch/install/share/lua/5.1/torch/init.lua:130: in function 'isTypeOf'
	/Users/ME/torch/install/share/lua/5.1/nn/utils.lua:43: in function 'recursiveType'
	/Users/ME/torch/install/share/lua/5.1/nn/Module.lua:123: in function 'type'
	/Users/ME/torch/install/share/lua/5.1/nn/utils.lua:45: in function 'recursiveType'
	/Users/ME/torch/install/share/lua/5.1/nn/utils.lua:41: in function 'recursiveType'
	/Users/ME/torch/install/share/lua/5.1/nn/Module.lua:123: in function 'cuda'
	./loadcaffe_wrapper.lua:73: in function 'load'
	neural_style.lua:53: in function 'main'
	neural_style.lua:365: in main chunk
	[C]: in function 'dofile'
	...ME/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x0109fd92f0

**Comment by jcjohnson** [comment]
Update your torch install: `luarocks install torch`

This was fixed very recently in https://github.com/torch/torch7/commit/52364bef5f3e1e8ff88d3134adbcc3f610ec72ee

**Comment by salamanders** [comment]
Yay that fixed it!

**facepalm - this laptop only has 1gb of GPU memory?  No wonder I keep getting out of memory errors.**
