### ISSUE TITLE
CUDA on Mac OS X?

### ISSUE THREAD

**Issue by 3DTOPO** [jcjohnson/neural-style#91]
I just installed a shiny new Titan X on my Hackintosh and have ran into some trouble trying to render on the GPU but got this error (after installing all the drivers, see below):

    CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-    6682/cutorch/lib/THC/THCGeneral.c:16
    stack traceback:
        	[C]: in function 'error'
        	/Users/jeshua/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
        	neural_style.lua:56: in function 'main'
        	neural_style.lua:480: in main chunk
        	[C]: in function 'dofile'
        	...shua/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        	[C]: at 0x010b454bd0

So I tried reinstalling torch and get this error:

    CMake Error at  /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
      Could NOT find CUDA: Found unsuitable version "3.2", but required is at
      least "5.5" (found /Developer/NVIDIA/CUDA-7.5)

I am confused because I installed 7.5 and it says 3.2 has been detected? Oh - I see - in the Cuda System Preference it says version 3.2.17:

<img width="742" alt="screen shot 2015-12-07 at 4 25 17 pm" src="https://cloud.githubusercontent.com/assets/352383/11643171/4c11ecdc-9cff-11e5-9457-4f7770158ff6.png">

Does that mean Mac OS X CUDA drivers are ancient compared to Ubuntu and thus unsupported? I just downloaded the most recent version of everything and installed fine. 
 
I roughly followed the Ubuntu instructions: I installed the official Web Driver for Mac OS X from here:
http://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/Mac/Quadro_Certified/346.03.03f02/WebDriver-346.03.03f02.pkg&lang=us&type=GeForce

Then cuda_7.5.20_mac.dmg from:
https://developer.nvidia.com/cuda-downloads

Then the CUDA Developer drivers from:
http://developer.download.nvidia.com/compute/cuda/3_2_prod/drivers/devdriver_3.2.17_macos.dmg

Then CUDA Toolkit: 
http://www.nvidia.com/object/thankyou.html?url=/compute/cuda/3_2_prod/toolkit/cudatoolkit_3.2.17_macos.pkg

I configured my paths with this:

    export PATH=$PATH:/Users/jeshua/torch/install/bin:/Developer/NVIDIA/CUDA-7.5/bin

**Comment by 3DTOPO** [comment]
I guess I will have to install this card and Ubuntu on another machine. Darn - I was hoping to use this card as my main card - seems pretty snappy. ;)

**Comment by jcjohnson** [comment]
Unfortunately I don't know much about configuring CUDA on OSX .... Sorry!

**Comment by 3DTOPO** [comment]
No worries, it really is a bit off topic! Apparently it is the version of the CUDA Toolkit that matters, and for that Mac OS X is stuck way back at 3.2 and 5.x is needed for Torch. I am just a bit surprised - the download page doesn't really make any note of that they are vastly different version of the toolkit.

**Comment by skabbit** [comment]
I'm pretty new in CUDA, but isn't it what you are searing for?
http://www.nvidia.com/object/macosx-cuda-5.5.47-driver.html

**Comment by 3DTOPO** [comment]
I *think* that link is for an even older version 5.5.47 for Mac OS X 10.9. I installed 7.5.20 and I am running on Mac OS X 10.11. If you look in my screenshot it says it is "Latest CUDA Driver Installed"

**Comment by geecko86** [comment]
@3DTOPO Any news? Seems like the Cuda toolkit 7.5 is available on Mac OS..
http://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html

**Comment by 3DTOPO** [comment]
@geecko86 I have not tried ever since I installed it on an Ubuntu machine. For all I know it works fine I was just doing something wrong. Sorry - I just don't know.

**Comment by SkyCrawl** [comment]
In case anyone has this problem in future (possibly after moving CUDA installation from the 'weird' directory `/Developer/...`), [this StackOverflow answer](http://stackoverflow.com/a/19981506) seems to be a way to fix if the relevant `cmake` call in torch's `install.sh` script is modified.

However, with CMake 3.6 and the latest Torch, there should be no trouble anymore as CUDA installation path seems to be determined automatically from the location of CUDA's compiler (`nvcc`) now. In other words, as long as you have correct PATH mapping, you should be fine.

**Comment by FuzzieLL** [comment]
I got the same problem too
`nit.lua:384: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-8150/cutorch/lib/THC/THCGeneral.c:91`

I downloaded the latest CUDA driver and installed it, but the CUDA preference shows like this:
<img width="663" alt="2016-10-14 3 48 08" src="https://cloud.githubusercontent.com/assets/13554785/19379662/adcc8966-9225-11e6-9fbc-e2c5f9107ac3.png">

how to fix it?

**Comment by SkyCrawl** [comment]
@FuzzieLL 
I got the same CUDA Driver version as you and suffer from other issues in regard to cutorch (see [here](https://github.com/torch/cutorch/issues/545#issuecomment-253663327) for details) but I never saw that error of yours. Do I suspect correctly that you installed CUDA Toolkit <= 7.5 sometime before and only upgraded the CUDA driver separately and recently? CUDA driver version 8.x is meant for CUDA Toolkit 8.x (not for earlier versions) so that's one possible explanation and a way to fix.
